# Generated by Django 4.0.2 on 2022-02-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0006_alter_user_last_login_alter_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='med_ensurance',
            new_name='med_insurance',
        ),
    ]
