# Generated by Django 4.0.2 on 2022-02-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0007_rename_med_ensurance_profile_med_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
